workimg updates

diff --git a/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client b/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client
--- a/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client
+++ b/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client
@@ -19,9 +19,22 @@ then
   exit 1
 fi
 
+#check the cts token
+vault read consul/creds/cts
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking Consul CTS acl token"
+  exit 1
+fi
+
 #aws
 aws_tgw=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/aws-us-east-1-terminating-gateway?dc=aws-us-east-1&passing=true")
 if [ "$(echo "${aws_tgw}" | jq '. | length')" != "1" ]; then
+  fail-message "AWS TGW is not healthy"
+  exit 1
+fi
+aws_cts=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/cts?dc=aws-us-east-1&passing=true")
+if [ "$(echo "${aws_cts}" | jq '. | length')" != "1" ]; then
   fail-message "AWS TGW is not healthy"
   exit 1
 fi
