working updates

diff --git a/instruqt-tracks/consul-hcs-on-azure/centralize-consul-secrets/check-cloud-client b/instruqt-tracks/consul-hcs-on-azure/centralize-consul-secrets/check-cloud-client
--- a/instruqt-tracks/consul-hcs-on-azure/centralize-consul-secrets/check-cloud-client
+++ b/instruqt-tracks/consul-hcs-on-azure/centralize-consul-secrets/check-cloud-client
@@ -6,8 +6,35 @@ if [ -f /tmp/skip-check ]; then
 fi
 
 vault login -method=userpass username=operations password=Password1
-vault read consul/creds/ops
 
+#check consul secret
+vault kv get -field ca secret/consul
+if [ $? -ne 0 ]
+then
+  fail-message "Could not get CA from Consul secret"
+  exit 1
+fi
+vault kv get -field gossip_key secret/consul
+if [ $? -ne 0 ]
+then
+  fail-message "Could not get gossip key from Consul secret"
+  exit 1
+fi
+vault kv get -field master_token secret/consul
+if [ $? -ne 0 ]
+then
+  fail-message "Could not get master token from Consul secret"
+  exit 1
+fi
+vault kv get -field retry_join secret/consul
+if [ $? -ne 0 ]
+then
+  fail-message "Could not get retry join from Consul secret"
+  exit 1
+fi
+
+#check dynamic role
+vault read consul/creds/ops
 if [ $? -ne 0 ]
 then
   fail-message "Could not get ops cred."
diff --git a/instruqt-tracks/consul-hcs-on-azure/configure-aks-cluster-secrets/check-cloud-client b/instruqt-tracks/consul-hcs-on-azure/configure-aks-cluster-secrets/check-cloud-client
--- a/instruqt-tracks/consul-hcs-on-azure/configure-aks-cluster-secrets/check-cloud-client
+++ b/instruqt-tracks/consul-hcs-on-azure/configure-aks-cluster-secrets/check-cloud-client
@@ -28,6 +28,13 @@ then
   exit 1
 fi
 
+kubectl get secret -n consul hashicorp-consul-ca-cert
+if [ $? -ne 0 ]
+then
+  fail-message "Could not get ca secret for frontend cluster."
+  exit 1
+fi
+
 kubectl config use-context backend-aks
 
 kubectl get secret -n consul hashicorp-consul-acl-config
@@ -48,6 +55,13 @@ kubectl get secret -n consul hashicorp-consul-gossip-key
 if [ $? -ne 0 ]
 then
   fail-message "Could not get gossip-key secret for backend cluster."
+  exit 1
+fi
+
+kubectl get secret -n consul hashicorp-consul-ca-cert
+if [ $? -ne 0 ]
+then
+  fail-message "Could not get ca secret for backend cluster."
   exit 1
 fi
 
diff --git a/instruqt-tracks/consul-hcs-on-azure/update-intentions/check-cloud-client b/instruqt-tracks/consul-hcs-on-azure/update-intentions/check-cloud-client
--- a/instruqt-tracks/consul-hcs-on-azure/update-intentions/check-cloud-client
+++ b/instruqt-tracks/consul-hcs-on-azure/update-intentions/check-cloud-client
@@ -5,34 +5,35 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
+#backend intentions
 vault login -method=userpass username=backend password=Password1
 export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/backend-developer)
-
 consul intention check frontend/web backend/api
 if [ $? -ne 0 ]
 then
   fail-message "Error checking web <> api intention."
   exit 1
 fi
-
 consul intention check backend/api backend/cache
 if [ $? -ne 0 ]
 then
   fail-message "Error checking api <> cache intention."
   exit 1
 fi
-
-consul intention check backend/api backend/payments
-if [ $? -ne 0 ]
-then
-  fail-message "Error checking api <> payments intention."
-  exit 1
-fi
-
-consul intention check backend/payments backend/currency
+consul intention check frontend/payments backend/currency
 if [ $? -ne 0 ]
 then
   fail-message "Error checking payments <> currency intention."
+  exit 1
+fi
+
+#frontend intentions
+vault login -method=userpass username=frontend password=Password1
+export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/frontend-developer)
+consul intention check backend/api frontend/payments
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking api <> payments intention."
   exit 1
 fi
 
