check packer VMs & loop check azure spn

diff --git a/instruqt-tracks/multi-cloud-service-networking-with-consul/01-provision-cloud-infra/check-cloud-client b/instruqt-tracks/multi-cloud-service-networking-with-consul/01-provision-cloud-infra/check-cloud-client
--- a/instruqt-tracks/multi-cloud-service-networking-with-consul/01-provision-cloud-infra/check-cloud-client
+++ b/instruqt-tracks/multi-cloud-service-networking-with-consul/01-provision-cloud-infra/check-cloud-client
@@ -1,18 +1,28 @@
 #!/bin/bash
 
-#aws - 2 new + default vpc
-echo "Checking AWS VNETs"
-aws_vpc=$(aws ec2 describe-vpcs | jq '[.. |."State"? | select(. == "available")] | length')
-if [ "${aws_vpc}" = "3" ]; then
-  exit 0
+#check images
+echo "Checking Packer Azure VM"
+azure_vm=$(az image list -g packer | jq length)
+if [ "${azure_vm}" != "1" ]; then
+  fail-message "Could not get Packer Azure VM. Rebuild w/Packer."
+  exit 1
 fi
-#should be 5 total VPCs
-if [ "${aws_vpc}" != "3" ]; then
-  fail-message "VPCs did not provision successful."
+echo "Checking Packer AWS AMI"
+aws_ami=$(aws ec2 describe-images --owners self | jq length)
+if [ "${aws_ami}" != "1" ]; then
+  fail-message "Could not get Packer AWS AMI. Rebuild w/Packer."
   exit 1
 fi
 
-#azure
+#aws vpc
+echo "Checking AWS VPCs"
+aws_vpc=$(aws ec2 describe-vpcs | jq '[.. |."State"? | select(. == "available")] | length')
+if [ "${aws_vpc}" != "3" ]; then
+  fail-message "AWS VPCs did not provision successful."
+  exit 1
+fi
+
+#azure vpc
 echo "Verifying Azure VNETs"
 rg=$(terraform output -state /root/terraform/infra/terraform.tfstate azure_rg_name)
 vnet_count=$(az network vnet list -g "${rg}" | jq '. | length')
@@ -20,22 +30,17 @@ if [ -z "$vnet_count" ]; then
       fail-message "Could not get Azure VNets. Check your Terraform."
       exit 1
 fi
-if [ "$vnet_count" = "2" ]; then
-  exit 0
-fi
 if [ "$vnet_count" != "2" ]; then
-  fail-message "VNETs did not provision successful."
+  fail-message "Azure VNETs did not provision successful."
   exit 1
 fi
 
-#gcp
+#gcp vpc
+echo "Verifying GCP VPCs"
 gcp_vpc=$(gcloud compute networks list --format=json | jq '. | length')
-if [ "${gcp_vpc}" = "2" ]; then
-  exit 0
-fi
-#should be 5 total VPCs
 if [ "${gcp_vpc}" != "3" ]; then
-  fail-message "VPCs did not provision successful."
+  fail-message "GCP VPCs did not provision successful."
   exit 1
 fi
+
 exit 0
