Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -252,6 +252,18 @@ jobs:
             cd /root/project/instruqt-tracks/network-infrastructure-automation
             echo "Running instruqt track push..."
             instruqt track push --force
+            echo "Running instruqt track test..."
+            # Retry instruqt track test up to 3 times
+            n=0
+            until [ $n -ge 3 ]; do
+              instruqt track test --skip-fail-check && break
+              n=$[$n+1]
+              sleep 60
+            done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
 workflows:
   version: 2
   build-and-deploy:
