acl checks

diff --git a/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client b/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client
--- a/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client
+++ b/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client
@@ -8,11 +8,27 @@ export CONSUL_HTTP_TOKEN=$(vault kv get -field master_token kv/consul)
 vault read consul/creds/replication
 if [ $? -ne 0 ]
 then
-  fail-message "Error checking relication token"
+  fail-message "Error checking Consul relication acl token"
   exit 1
 fi
 
-#check on demand creds
+#check the mgw token
+vault read consul/creds/mgw
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking Consul mgw acl token"
+  exit 1
+fi
+
+#check the vault token
+vault read consul/creds/vault
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking Consul vault acl token"
+  exit 1
+fi
+
+#check operator creds
 vault read consul/creds/operator
 if [ $? -ne 0 ]
 then
diff --git a/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client b/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client
--- a/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client
+++ b/instruqt-tracks/multi-cloud-service-networking-with-consul/13-provision-consul-terminating-gateways/check-cloud-client
@@ -3,6 +3,22 @@
 #creds
 vault login -method=userpass username=admin password=admin
 
+#check the esm token
+vault read consul/creds/aws-tgw
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking Consul AWS TGW acl token"
+  exit 1
+fi
+
+#check the esm token
+vault read consul/creds/azure-tgw
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking Consul Azure TGW acl token"
+  exit 1
+fi
+
 #aws
 aws_tgw=$(curl -s -H "X-Consul-Token: $(vault kv get -field master_token kv/consul)" "${CONSUL_HTTP_ADDR}/v1/health/service/aws-us-east-1-terminating-gateway?dc=aws-us-east-1&passing=true")
 if [ "$(echo "${aws_tgw}" | jq '. | length')" != "1" ]; then
