check the agent token [ci skip]

diff --git a/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client b/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client
--- a/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client
+++ b/instruqt-tracks/multi-cloud-service-networking-with-consul/06-bootstrap-consul-primary/check-cloud-client
@@ -12,6 +12,14 @@ then
   exit 1
 fi
 
+#check the agent token
+vault read consul/creds/agent
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking Consul agent acl token"
+  exit 1
+fi
+
 #check the mgw token
 vault read consul/creds/mgw
 if [ $? -ne 0 ]
