updates

diff --git a/instruqt-tracks/pan-azure-network-infrastructure-automation/track_scripts/setup-workstation b/instruqt-tracks/pan-azure-network-infrastructure-automation/track_scripts/setup-workstation
--- a/instruqt-tracks/pan-azure-network-infrastructure-automation/track_scripts/setup-workstation
+++ b/instruqt-tracks/pan-azure-network-infrastructure-automation/track_scripts/setup-workstation
@@ -41,8 +41,8 @@ fi
 
 #get assets
 echo "cloning assets..."
-git clone https://github.com/hashicorp/field-workshops-consul.git
-cp -r field-workshops-consul/instruqt-tracks/network-infrastructure-automation/assets/terraform /root/terraform
+git clone --branch pan-azure-nia https://github.com/hashicorp/field-workshops-consul.git
+cp -r field-workshops-consul/instruqt-tracks/pan-azure-network-infrastructure-automation/assets/terraform /root/terraform
 rm -rf field-workshops-consul
 
 #ssh agent
@@ -58,94 +58,74 @@ az account set --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION
 
 #enable marketplace
 az provider register --namespace 'Microsoft.Solutions' --subscription "${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}"
-az vm image terms accept --urn paloaltonetworks:vmseries1:bundle1:latest
+az vm image terms accept --urn paloaltonetworks:vmseries-flex:bundle1:latest
 
 #optimistic provisioning
 echo "starting optimistic provisioning..."
 
 #vnets
-cd /root/terraform/vnet
+cd /root/terraform/01-deploy-infra
 /usr/bin/terraform init
-cat << EOF > /root/terraform/vnet/terraform.tfvars
-ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
-EOF
+# cat << EOF > /root/terraform/01-deploy-infra/terraform.tfvars
+# ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
+# EOF
 terraform apply -auto-approve 2>&1 | tee terraform.out
 
-#consul
-cd /root/terraform/consul-server
-terraform init
-cat << EOF > /root/terraform/consul-server/terraform.tfvars
-ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
-EOF
-nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
+# #consul
+# cd /root/terraform/consul-server
+# terraform init
+# cat << EOF > /root/terraform/consul-server/terraform.tfvars
+# ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
+# EOF
+# nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
 
-#vault
-cd /root/terraform/vault
-terraform init
-cat << EOF > /root/terraform/vault/terraform.tfvars
-ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
-EOF
-nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
+# #vault
+# cd /root/terraform/vault
+# terraform init
+# cat << EOF > /root/terraform/vault/terraform.tfvars
+# ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
+# EOF
+# nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
 
-#f5
-cd /root/terraform/bigip
-terraform init
-terraform import azurerm_marketplace_agreement.f5 "/subscriptions/${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}/providers/Microsoft.MarketplaceOrdering/agreements/f5-networks/offers/f5-big-ip-good/plans/f5-bigip-virtual-edition-25m-good-hourly"
-nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
+# #f5
+# cd /root/terraform/bigip
+# terraform init
+# terraform import azurerm_marketplace_agreement.f5 "/subscriptions/${INSTRUQT_AZURE_SUBSCRIPTION_CONSUL_SUBSCRIPTION_ID}/providers/Microsoft.MarketplaceOrdering/agreements/f5-networks/offers/f5-big-ip-good/plans/f5-bigip-virtual-edition-25m-good-hourly"
+# nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
 
-#panw
-cd /root/terraform/panw-vm
-terraform init
-nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
+# #panw
+# cd /root/terraform/02-configure-infra
+# terraform init
+# nohup terraform apply -auto-approve 2>&1 | tee nohup.out &
 
-#wait for f5 & panw
-echo "Waiting for network devices..."
-sleep 600
+# #wait for f5 & panw
+# echo "Waiting for network devices..."
+# sleep 300
 
-#check devices
-echo "Running pre-flight checks..."
+# #check devices
+# echo "Running pre-flight checks..."
 
-#f5
-echo "Checking PANW FW"
-n=0
-until [ $n -ge 10 ]; do
-  echo "Fetching PANW..."
-  firewall_ip=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate FirewallIP)
-  pa_username=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate pa_username)
-  pa_password=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate pa_password)
-  if [ "$(curl -sk -o /dev/null  -u ${pa_username}:${pa_password} -w ''%{http_code}'' https://${firewall_ip}/restapi/v9.1/Device/VirtualSystems)" = "200" ]; then
-      break
-  fi
-  n=$[$n+1]
-  sleep 60
-done
-if [ $n -ge 10 ]; then
-  fail-message "Could not check PANW."
-  exit 1
-fi
+# #pan
+# echo "Checking PANW FW"
+# n=0
+# until [ $n -ge 10 ]; do
+#   echo "Fetching PANW..."
+#   firewall_ip=$(terraform output -state /root/terraform/01-deploy-infra/terraform.tfstate FirewallIP)
+#   pa_username=$(terraform output -state /root/terraform/01-deploy-infra/terraform.tfstate pa_username)
+#   pa_password=$(terraform output -state /root/terraform/01-deploy-infra/terraform.tfstate pa_password)
+#   if [ "$(curl -sk -o /dev/null  -u ${pa_username}:${pa_password} -w ''%{http_code}'' https://${firewall_ip}/restapi/v10.1.1/Device/VirtualSystems)" = "200" ]; then
+#       break
+#   fi
+#   n=$[$n+1]
+#   sleep 60
+# done
+# if [ $n -ge 10 ]; then
+#   fail-message "Could not check PANW."
+#   exit 1
+# fi
 
-#panw
-echo "Checking F5 BIG-IP"
-n=0
-until [ $n -ge 5 ]; do
-  echo "Fetching BIG-IP..."
-  f5_url=$(terraform output -state /root/terraform/bigip/terraform.tfstate mgmt_url)
-  f5_username=$(terraform output -state /root/terraform/bigip/terraform.tfstate f5_username)
-  f5_password=$(terraform output -state /root/terraform/bigip/terraform.tfstate f5_password)
-  f5_status=$(curl -s -k -u "${f5_username}:${f5_password}" -H "Content-Type: application/json" -o /dev/null -w "%{http_code}" "${f5_url}/mgmt/tm/cm/device/")
-  if [ "${f5_status}" = "200" ]; then
-    break
-  fi
-  n=$[$n+1]
-  sleep 60
-done
-if [ $n -ge 5 ]; then
-  fail-message "Could not check BIG-IP."
-  exit 1
-fi
-
-#wait for network device boot up
-echo "Network Devices up! Waiting for init processes..."
-sleep 300
+# #wait for network device boot up
+# echo "Network Devices up! Waiting for init processes..."
+# sleep 300
 
 exit 0
