working updates

diff --git a/instruqt-tracks/consul-enterprise-on-aws/provision-consul/check-cloud-client b/instruqt-tracks/consul-enterprise-on-aws/provision-consul/check-cloud-client
--- a/instruqt-tracks/consul-enterprise-on-aws/provision-consul/check-cloud-client
+++ b/instruqt-tracks/consul-enterprise-on-aws/provision-consul/check-cloud-client
@@ -1,10 +1,16 @@
 #!/bin/bash
 
 env=$(/usr/local/bin/terraform output -state /root/terraform/consul/terraform.tfstate env)
+
+if [ -z "$env" ]; then
+  fail-message "Could not get Consul env from state."
+  exit 1
+fi
+
 asg=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names ${env}-consul-0.0.1 |  jq '.AutoScalingGroups | length')
 
 if [ $asg != "1" ]; then
-  fail-message "ASG did not provision successful."
+  fail-message "ASG did not provision successful. Did not find 0.0.1 version."
   exit 1
 fi
 
