merge commit

diff --git a/instruqt-tracks/multi-cloud-service-networking-with-consul/04-centralize-secrets-in-vault/check-cloud-client b/instruqt-tracks/multi-cloud-service-networking-with-consul/04-centralize-secrets-in-vault/check-cloud-client
--- a/instruqt-tracks/multi-cloud-service-networking-with-consul/04-centralize-secrets-in-vault/check-cloud-client
+++ b/instruqt-tracks/multi-cloud-service-networking-with-consul/04-centralize-secrets-in-vault/check-cloud-client
@@ -220,4 +220,33 @@ then
   fail-message "Error getting Consul bootstrap secret. Check KV access."
   exit 1
 fi
+
+#check jwt for auto config
+iam_meta=$(vault read /auth/aws/config/identity -format=json | jq -r .data.iam_metadata[0])
+if [ "${iam_meta}" != "client_arn" ]; then
+  fail-message "Error AWS IAM meta is not client_arn."
+  exit 1
+fi
+
+vault read identity/oidc/key/consul
+if [ $? -ne 0 ]
+then
+  fail-message "Error getting Consul OIDC key."
+  exit 1
+fi
+
+vault read identity/oidc/role/consul-aws-us-east-1
+if [ $? -ne 0 ]
+then
+  fail-message "Error getting AWS OIDC role."
+  exit 1
+fi
+
+vault read identity/oidc/role/consul-azure-west-us-2
+if [ $? -ne 0 ]
+then
+  fail-message "Error getting AZURE OIDC role."
+  exit 1
+fi
+
 exit 0
