working updates

diff --git a/instruqt-tracks/consul-enterprise-on-aws/update-intentions/check-cloud-client b/instruqt-tracks/consul-enterprise-on-aws/update-intentions/check-cloud-client
--- a/instruqt-tracks/consul-enterprise-on-aws/update-intentions/check-cloud-client
+++ b/instruqt-tracks/consul-enterprise-on-aws/update-intentions/check-cloud-client
@@ -1,11 +1,33 @@
 #!/bin/bash
 
-kubectl config use-context eks_frontend
-endpoint=$(kubectl get services web -o json | jq -r .status.loadBalancer.ingress[0].hostname)
-api=$(curl -s -o /dev/null -w "%{http_code}" "${endpoint}")
+vault login -method=userpass username=backend password=Password1
+export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/backend-developer)
 
-if [ "${api}" != "200" ]; then
-  fail-message "Your service did not return a 200."
+consul intention check frontend/web backend/api
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking web <> api intention."
+  exit 1
+fi
+
+consul intention check backend/api backend/cache
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking api <> cache intention."
+  exit 1
+fi
+
+consul intention check backend/api backend/payments
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking api <> payments intention."
+  exit 1
+fi
+
+consul intention check backend/payments backend/currency
+if [ $? -ne 0 ]
+then
+  fail-message "Error checking payments <> currency intention."
   exit 1
 fi
 
