Testing slack notifications

diff --git a/.github/workflows/instruqt-track-test.yml b/.github/workflows/instruqt-track-test.yml
--- a/.github/workflows/instruqt-track-test.yml
+++ b/.github/workflows/instruqt-track-test.yml
@@ -20,6 +20,8 @@ env:
 jobs:
   test-track:
     runs-on: ubuntu-latest
+    outputs:
+      test_runs: ${{ steps.instruqt-test.outputs.runs }}
     steps:
     - name: Checkout Source
       id: checkout-source
@@ -37,14 +39,18 @@ jobs:
       id: instruqt-test
       working-directory: ${{ inputs.working_directory }}
       run: |-
-        n=0
-        until [ $n -ge 3 ]; do
-          echo "Test $n"
-          instruqt track test --skip-fail-check && break
-          n=$(( n +1 ))
-          sleep 60
-        done
-        if [ $n -ge 3 ]; then
-          echo "Instruqt track test failed after $n attempts"
-          exit 1
-        fi
+        echo "runs=1" >> "${GITHUB_OUTPUT}"
+        exit 0
+##       run: |-
+##         n=0
+##         until [ $n -ge 3 ]; do
+##           echo "Test $n"
+##           instruqt track test --skip-fail-check && break
+##           n=$(( n +1 ))
+##           sleep 60
+##         done
+##         echo "runs=${n}" >> "${GITHUB_OUTPUT}"
+##         if [ $n -ge 3 ]; then
+##           echo "Instruqt track test failed after $n attempts"
+##           exit 1
+##         fi
